version: '3'

services:
  db:
    env_file: .env
    build: ./docker/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    hostname: phpmyadmin.local
    links:
        - db
    ports:
        - 8181:80
  webserver:
    container_name: webserver
    build: 
      context: .
      dockerfile: ./docker/webserver/Dockerfile
      args:
        - PROJECT=project
    ports:
      - 9000:80
    volumes:
      - ./project:/var/www/project #project must be created
    depends_on:
      - db
  react:
    container_name: react_app
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    ports:
      - 3000:3000
    links:
      - webserver  
    volumes:
      - ./react:/usr/src/app
    command: yarn start  
volumes:
  db:  